SETUP_FUNCTION = True
LEARN_FUNCTION = True #FIXME fails on false due to NUMBA SHAPE RESTRICTIONS
METALEVEL_COUNT = 3

SETUP_OP_DEPTH = 10
PRED_OP_DEPTH = 10
LEARN_OP_DEPTH = 10
max_OP_depth = max(SETUP_OP_DEPTH, PRED_OP_DEPTH, LEARN_OP_DEPTH)
OP_DEPTH = max(SETUP_OP_DEPTH, PRED_OP_DEPTH, LEARN_OP_DEPTH)

X_SHAPE = ()

POPULATION_COUNT = 100
TOURNAMENT_COUNT = 10
ITERS = 5000000


SETUP_OP_NUMBER = 4
PRED_OP_NUMBER = 4
LEARN_OP_NUMBER = 4

NUMBER_OF_META_OPS = 4
METALEVEL_COUNT = 3
NUMBER_OF_OPS = 12
PRIOR_LEVEL_OPS = 3

SETUP_OP_DEPTH = 10
PRED_OP_DEPTH = 10
LEARN_OP_DEPTH = 5

### Memory Array 
scalars = 3
vectors = 3
matricies = 3

MAX_ARG = 2
