BETA = 0.05

MAXIMUM_ARGUMENT_LENGTH = 2
INPUT_SIZE = 1
MEMORY_SIZE = 5 + INPUT_SIZE
MATRIX_SIZE = (5,1) #FIXME doesn't allow for values not == X_val
POPULATION_COUNT = 1000
TOURNAMENT_COUNT = 10
ITERS = 1000000

INPUT_ADDR = 0
OUTPUT_ADDR = 1
INPUT_CONST_A = 2
INPUT_CONST_B = 3
INPUT_CONST_C = 4

OUTPUT_VECTOR_POS = 5
OUTPUT_MATRIX_POS_1 = 6
OUTPUT_MATRIX_POS_2 = 7
#OUTPUT_SHAPE = ()

N_ARGS = 2
OP_DEPTH = 5

MIN_VAL = -1
MIN_FITNESS = 999999